#!/bin/bash

set -e

clear_vendor_checksums() {
	sed -i 's/\("files":{\)[^}]*/\1/' vendor/$1/.cargo-checksum.json
}

export CWD="$(pwd)"
export STUFF="$CWD/stuff"
export OUT="$CWD/out"
export SRC="$OUT/src"
export TOOLS="$OUT/tools"

export RUSTVER="1.45.0"

export LC_ALL="POSIX"
export HOSTCC="gcc"
export HOSTCXX="g++"
export XHOST="$(echo ${MACHTYPE} | sed -e 's/-[^-]*/-cross/')"
export PATH="$SRC/bin:$PATH"

if [ -z $MKOPTS ]; then
	export MKJOBS="$(expr $(nproc) + 1)"
fi

export MKOPTS="-j$MKJOBS"

rm -rf $OUT
mkdir -p $SRC $TOOLS

if [ "$TOOLCHAIN" != "no" ]; then
	cd "$SRC"
	for i in x86_64-linux-musl i686-linux-musl aarch64-linux-musl \
		powerpc64le-linux-musl powerpc64-linux-musl powerpc-linux-musl; do
		wget http://more.musl.cc/10/x86_64-linux-musl/$i-cross.tgz
		wget http://pkg.musl.cc/libexecinfo/$i.tgz -O libexecinfo-$i.tgz
		wget http://pkg.musl.cc/openssl/$i.tgz -O openssl-$i.tgz
		bsdtar -xvf $i-cross.tgz
		bsdtar -C "$SRC"/$i-cross -xvf libexecinfo-$i.tgz
		bsdtar -C "$SRC"/$i-cross -xvf openssl-$i.tgz
		export PATH="$SRC/$i-cross/bin:$PATH"
	done
fi

cd $SRC
wget https://static.rust-lang.org/dist/rustc-$RUSTVER-src.tar.gz
bsdtar -xvf rustc-$RUSTVER-src.tar.gz
cd rustc-$RUSTVER-src

patch -Np1 -i "$STUFF"/musl.patch
patch -Np1 -i "$STUFF"/libressl.patch
patch -Np1 -i "$STUFF"/0015-Use-ELFv2-ABI-on-all-powerpc64-targets.patch

clear_vendor_checksums libc
clear_vendor_checksums openssl-src
clear_vendor_checksums openssl-sys

cat << EOF > config.toml
[llvm]
optimize = true
release-debuginfo = false
assertions = false
static-libstdcpp = true
ninja = true
targets = "AArch64;X86;PowerPC"

[build]
host = [
  "x86_64-unknown-linux-musl",
  "i686-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "powerpc64le-unknown-linux-musl",
  "powerpc64-unknown-linux-musl",
  "powerpc-unknown-linux-musl"
]
cargo = "$(which cargo)"
rustc = "$(which rustc)"
docs = false
compiler-docs  = false
extended = true
submodules = false
python = "python3"
locked-deps = true
vendor = true
cargo-native-static = true
sanitizers = false
profiler = false
full-bootstrap = false

[rust]
channel = "nightly"
rpath  = false
codegen-units = 1
debuginfo-level = 0
debug = false
backtrace = false
jemalloc = false
debug-assertions = false
codegen-tests = false
deny-warnings = false

[target.x86_64-unknown-linux-musl]
cc = "x86_64-linux-musl-gcc"
cxx = "x86_64-linux-musl-g++"
linker = "x86_64-linux-musl-gcc"
musl-root = "$SRC/x86_64-linux-musl-cross/x86_64-linux-musl"
crt-static = false

[target.i686-unknown-linux-musl]
cc = "i686-linux-musl-gcc"
cxx = "i686-linux-musl-g++"
linker = "i686-linux-musl-gcc"
musl-root = "$SRC/i686-linux-musl-cross/i686-linux-musl"
crt-static = false

[target.aarch64-unknown-linux-musl]
cc = "aarch64-linux-musl-gcc"
cxx = "aarch64-linux-musl-g++"
linker = "aarch64-linux-musl-gcc"
musl-root = "$SRC/aarch64-linux-musl-cross/aarch64-linux-musl"
crt-static = false

[target.powerpc64le-unknown-linux-musl]
cc = "powerpc64le-linux-musl-gcc"
cxx = "powerpc64le-linux-musl-g++"
linker = "powerpc64le-linux-musl-gcc"
musl-root = "$SRC/powerpc64le-linux-musl-cross/powerpc64le-linux-musl"
crt-static = false

[target.powerpc64-unknown-linux-musl]
cc = "powerpc64-linux-musl-gcc"
cxx = "powerpc64-linux-musl-g++"
linker = "powerpc64-linux-musl-gcc"
musl-root = "$SRC/powerpc64-linux-musl-cross/powerpc64-linux-musl"
crt-static = false

[target.powerpc-unknown-linux-musl]
cc = "powerpc-linux-musl-gcc"
cxx = "powerpc-linux-musl-g++"
linker = "powerpc-linux-musl-gcc"
musl-root = "$SRC/powerpc-linux-musl-cross/powerpc-linux-musl"
crt-static = false
EOF

export RUST_BACKTRACE=1
export X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="$SRC/x86_64-linux-musl-cross/x86_64-linux-musl"
export I686_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="$SRC/i686-linux-musl-cross/i686-linux-musl"
export AARCH64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="$SRC/aarch64-linux-musl-cross/aarch64-linux-musl"
export POWERPC64LE_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="$SRC/powerpc64le-linux-musl-cross/powerpc64le-linux-musl"
export POWERPC64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="$SRC/powerpc64-linux-musl-cross/powerpc64-linux-musl"
export POWERPC_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="$SRC/powerpc-linux-musl-cross/powerpc-linux-musl"

./x.py build -j$MKJOBS
